// src/components/ui/interactive-grid-pattern/InteractiveGridPattern.vue
<script lang="ts" setup>
import type { HTMLAttributes } from "vue";
import { computed, ref } from "vue";

interface InteractiveGridPatternProps {
  className?: HTMLAttributes["class"];
  squaresClassName?: HTMLAttributes["class"];
  width?: number;
  height?: number;
  squares?: [number, number];
}

const props = withDefaults(defineProps<InteractiveGridPatternProps>(), {
  width: 50,
  height: 50,
  squares: () => [24, 24],
});

const horizontal = computed(() => props.squares[0]);
const vertical = computed(() => props.squares[1]);

const totalSquares = computed(() => horizontal.value * vertical.value);

const hoveredSquare = ref<number | null>(null);

const gridWidth = computed(() => props.width * horizontal.value);
const gridHeight = computed(() => props.height * vertical.value);

function getX(index: number) {
  return (index % horizontal.value) * props.width;
}

function getY(index: number) {
  return Math.floor(index / horizontal.value) * props.height;
}

const svgClass = computed(() => [
  "absolute inset-0 h-full w-full border border-gray-400/30",
  props.className,
]);

function getRectClass(index: number) {
  return [
    "stroke-gray-400/30 transition-all duration-100 ease-in-out not-[&:hover]:duration-1000",
    hoveredSquare.value === index ? "fill-gray-300/30" : "fill-transparent",
    props.squaresClassName,
  ];
}

function handleMouseEnter(index: number) {
  hoveredSquare.value = index;
}

function handleMouseLeave() {
  hoveredSquare.value = null;
}
</script>

<template>
  <svg
    :width="gridWidth"
    :height="gridHeight"
    :class="svgClass"
  >
    <rect
      v-for="(_, index) in totalSquares"
      :key="index"
      :x="getX(index)"
      :y="getY(index)"
      :width="width"
      :height="height"
      :class="getRectClass(index)"
      @mouseenter="handleMouseEnter(index)"
      @mouseleave="handleMouseLeave"
    />
  </svg>
</template>

// src/features/home/components/InteractiveGridPattern.tsx
import { useState } from "react";

type InteractiveGridPatternProps = {
  className?: string;
  squaresClassName?: string;
  width?: number;
  height?: number;
  squares?: [number, number];
};

export default function InteractiveGridPattern({
  className,
  squaresClassName,
  width = 40,
  height = 40,
  squares = [24, 24],
}: InteractiveGridPatternProps) {
  const [hoveredSquare, setHoveredSquare] = useState<number | null>(null);
  const [horizontal, vertical] = squares;
  const totalSquares = horizontal * vertical;

  const getRectClass = (index: number) => {
    const base =
      "stroke-gray-400/30 transition-all duration-100 ease-in-out [&:not(:hover)]:duration-1000";
    const fill = hoveredSquare === index ? "fill-gray-300/30" : "fill-transparent";
    return `${base} ${fill} ${squaresClassName ?? ""}`.trim();
  };

  return (
    <svg
      width={width * horizontal}
      height={height * vertical}
      className={`absolute inset-0 h-full w-full border border-gray-400/30 ${className ?? ""}`.trim()}
      aria-hidden="true"
    >
      {Array.from({ length: totalSquares }).map((_, index) => (
        <rect
          key={index}
          x={(index % horizontal) * width}
          y={Math.floor(index / horizontal) * height}
          width={width}
          height={height}
          className={getRectClass(index)}
          onMouseEnter={() => setHoveredSquare(index)}
          onMouseLeave={() => setHoveredSquare(null)}
        />
      ))}
    </svg>
  );
}
